/*
 * siastats.info API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2021-03-10
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package siastats

import (
	"encoding/json"
)

// PlotBandLabel struct for PlotBandLabel
type PlotBandLabel struct {
	Text      *string `json:"text,omitempty"`
	Rotation  *int32  `json:"rotation,omitempty"`
	TextAlign *string `json:"textAlign,omitempty"`
	Align     *string `json:"align,omitempty"`
	X         *int32  `json:"x,omitempty"`
	Y         *int32  `json:"y,omitempty"`
}

// NewPlotBandLabel instantiates a new PlotBandLabel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlotBandLabel() *PlotBandLabel {
	this := PlotBandLabel{}
	return &this
}

// NewPlotBandLabelWithDefaults instantiates a new PlotBandLabel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlotBandLabelWithDefaults() *PlotBandLabel {
	this := PlotBandLabel{}
	return &this
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *PlotBandLabel) GetText() string {
	if o == nil || o.Text == nil {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlotBandLabel) GetTextOk() (*string, bool) {
	if o == nil || o.Text == nil {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *PlotBandLabel) HasText() bool {
	if o != nil && o.Text != nil {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *PlotBandLabel) SetText(v string) {
	o.Text = &v
}

// GetRotation returns the Rotation field value if set, zero value otherwise.
func (o *PlotBandLabel) GetRotation() int32 {
	if o == nil || o.Rotation == nil {
		var ret int32
		return ret
	}
	return *o.Rotation
}

// GetRotationOk returns a tuple with the Rotation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlotBandLabel) GetRotationOk() (*int32, bool) {
	if o == nil || o.Rotation == nil {
		return nil, false
	}
	return o.Rotation, true
}

// HasRotation returns a boolean if a field has been set.
func (o *PlotBandLabel) HasRotation() bool {
	if o != nil && o.Rotation != nil {
		return true
	}

	return false
}

// SetRotation gets a reference to the given int32 and assigns it to the Rotation field.
func (o *PlotBandLabel) SetRotation(v int32) {
	o.Rotation = &v
}

// GetTextAlign returns the TextAlign field value if set, zero value otherwise.
func (o *PlotBandLabel) GetTextAlign() string {
	if o == nil || o.TextAlign == nil {
		var ret string
		return ret
	}
	return *o.TextAlign
}

// GetTextAlignOk returns a tuple with the TextAlign field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlotBandLabel) GetTextAlignOk() (*string, bool) {
	if o == nil || o.TextAlign == nil {
		return nil, false
	}
	return o.TextAlign, true
}

// HasTextAlign returns a boolean if a field has been set.
func (o *PlotBandLabel) HasTextAlign() bool {
	if o != nil && o.TextAlign != nil {
		return true
	}

	return false
}

// SetTextAlign gets a reference to the given string and assigns it to the TextAlign field.
func (o *PlotBandLabel) SetTextAlign(v string) {
	o.TextAlign = &v
}

// GetAlign returns the Align field value if set, zero value otherwise.
func (o *PlotBandLabel) GetAlign() string {
	if o == nil || o.Align == nil {
		var ret string
		return ret
	}
	return *o.Align
}

// GetAlignOk returns a tuple with the Align field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlotBandLabel) GetAlignOk() (*string, bool) {
	if o == nil || o.Align == nil {
		return nil, false
	}
	return o.Align, true
}

// HasAlign returns a boolean if a field has been set.
func (o *PlotBandLabel) HasAlign() bool {
	if o != nil && o.Align != nil {
		return true
	}

	return false
}

// SetAlign gets a reference to the given string and assigns it to the Align field.
func (o *PlotBandLabel) SetAlign(v string) {
	o.Align = &v
}

// GetX returns the X field value if set, zero value otherwise.
func (o *PlotBandLabel) GetX() int32 {
	if o == nil || o.X == nil {
		var ret int32
		return ret
	}
	return *o.X
}

// GetXOk returns a tuple with the X field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlotBandLabel) GetXOk() (*int32, bool) {
	if o == nil || o.X == nil {
		return nil, false
	}
	return o.X, true
}

// HasX returns a boolean if a field has been set.
func (o *PlotBandLabel) HasX() bool {
	if o != nil && o.X != nil {
		return true
	}

	return false
}

// SetX gets a reference to the given int32 and assigns it to the X field.
func (o *PlotBandLabel) SetX(v int32) {
	o.X = &v
}

// GetY returns the Y field value if set, zero value otherwise.
func (o *PlotBandLabel) GetY() int32 {
	if o == nil || o.Y == nil {
		var ret int32
		return ret
	}
	return *o.Y
}

// GetYOk returns a tuple with the Y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlotBandLabel) GetYOk() (*int32, bool) {
	if o == nil || o.Y == nil {
		return nil, false
	}
	return o.Y, true
}

// HasY returns a boolean if a field has been set.
func (o *PlotBandLabel) HasY() bool {
	if o != nil && o.Y != nil {
		return true
	}

	return false
}

// SetY gets a reference to the given int32 and assigns it to the Y field.
func (o *PlotBandLabel) SetY(v int32) {
	o.Y = &v
}

func (o PlotBandLabel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Text != nil {
		toSerialize["text"] = o.Text
	}
	if o.Rotation != nil {
		toSerialize["rotation"] = o.Rotation
	}
	if o.TextAlign != nil {
		toSerialize["textAlign"] = o.TextAlign
	}
	if o.Align != nil {
		toSerialize["align"] = o.Align
	}
	if o.X != nil {
		toSerialize["x"] = o.X
	}
	if o.Y != nil {
		toSerialize["y"] = o.Y
	}
	return json.Marshal(toSerialize)
}

type NullablePlotBandLabel struct {
	value *PlotBandLabel
	isSet bool
}

func (v NullablePlotBandLabel) Get() *PlotBandLabel {
	return v.value
}

func (v *NullablePlotBandLabel) Set(val *PlotBandLabel) {
	v.value = val
	v.isSet = true
}

func (v NullablePlotBandLabel) IsSet() bool {
	return v.isSet
}

func (v *NullablePlotBandLabel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlotBandLabel(val *PlotBandLabel) *NullablePlotBandLabel {
	return &NullablePlotBandLabel{value: val, isSet: true}
}

func (v NullablePlotBandLabel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlotBandLabel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
