/*
 * siastats.info API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2019-10-03
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package siastats
// HashResponse struct for HashResponse
type HashResponse struct {
	Type string `json:"Type,omitempty"`
	MasterHash string `json:"MasterHash,omitempty"`
	BalanceSc float64 `json:"balanceSc,omitempty"`
	ReceivedSc float64 `json:"receivedSc,omitempty"`
	SentSc float64 `json:"sentSc,omitempty"`
	BalanceSf float32 `json:"balanceSf,omitempty"`
	TotalTxCount int32 `json:"TotalTxCount,omitempty"`
	FirstSeen int32 `json:"firstSeen,omitempty"`
	Last100Transactions []Transaction `json:"last100Transactions,omitempty"`
}
