/*
 * siastats.info API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2019-10-03
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package siastats
// AllHostsRequest struct for AllHostsRequest
type AllHostsRequest struct {
	Network string `json:"network"`
	List string `json:"list"`
}
