/*
 * siastats.info API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2019-10-03
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package siastats
// Ticks struct for Ticks
type Ticks struct {
	Total [][]float32 `json:"total,omitempty"`
	Used [][]float32 `json:"used,omitempty"`
	Storage [][]float32 `json:"storage,omitempty"`
	Bandwidth [][]float32 `json:"bandwidth,omitempty"`
	Collateral [][]float32 `json:"collateral,omitempty"`
}
