/*
 * siastats.info API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2019-10-03
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package siastats
// Host struct for Host
type Host struct {
	Id float32 `json:"Id,omitempty"`
	Online bool `json:"Online,omitempty"`
	Pubkey string `json:"Pubkey,omitempty"`
	CurrentIp string `json:"CurrentIp,omitempty"`
	CountryCode string `json:"CountryCode,omitempty"`
	TotalStorage float32 `json:"TotalStorage,omitempty"`
	AcceptingContracts bool `json:"AcceptingContracts,omitempty"`
	Version string `json:"Version,omitempty"`
	UsedStorage float32 `json:"UsedStorage,omitempty"`
	Collateral int32 `json:"Collateral,omitempty"`
	ContractPrice int32 `json:"ContractPrice,omitempty"`
	StoragePrice int32 `json:"StoragePrice,omitempty"`
	UploadPrice int32 `json:"UploadPrice,omitempty"`
	DownloadPrice int32 `json:"DownloadPrice,omitempty"`
	Rank int32 `json:"Rank,omitempty"`
	FinalScore int32 `json:"FinalScore,omitempty"`
	ErrorType string `json:"ErrorType,omitempty"`
}
