/*
 * siastats.info API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2019-10-03
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package siastats
// Transaction struct for Transaction
type Transaction struct {
	MasterHash string `json:"MasterHash,omitempty"`
	ScChange float64 `json:"ScChange,omitempty"`
	SfChange float32 `json:"SfChange,omitempty"`
	Height int32 `json:"Height,omitempty"`
	Timestamp string `json:"Timestamp,omitempty"`
	TxType string `json:"TxType,omitempty"`
}
