/*
 * siastats.info API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2019-10-03
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package siastats
// HostResponse struct for HostResponse
type HostResponse struct {
	RequestStatus string `json:"requestStatus,omitempty"`
	Id int32 `json:"id,omitempty"`
	Online bool `json:"online,omitempty"`
	Rank int32 `json:"rank,omitempty"`
	Network string `json:"network,omitempty"`
	Pubkey string `json:"pubkey,omitempty"`
	Ip string `json:"ip,omitempty"`
	Lon float32 `json:"lon,omitempty"`
	Lat float32 `json:"lat,omitempty"`
	Isp string `json:"isp,omitempty"`
	CountryCode string `json:"countryCode,omitempty"`
	CountryName string `json:"countryName,omitempty"`
	MaxDuration float32 `json:"maxDuration,omitempty"`
	TotalStorage float32 `json:"totalStorage,omitempty"`
	UsedStorage float32 `json:"usedStorage,omitempty"`
	Collateral float32 `json:"collateral,omitempty"`
	StoragePrice float32 `json:"storagePrice,omitempty"`
	UploadPrice float32 `json:"uploadPrice,omitempty"`
	DownloadPrice float32 `json:"downloadPrice,omitempty"`
	MinContractPrice float32 `json:"minContractPrice,omitempty"`
	FirstSeenBlock int32 `json:"firstSeenBlock,omitempty"`
	Version string `json:"version,omitempty"`
	SectorSize int32 `json:"sectorSize,omitempty"`
	WindowSize int32 `json:"windowSize,omitempty"`
	SeenBy []string `json:"seenBy,omitempty"`
	Benchmarks Benchmarks `json:"benchmarks,omitempty"`
	ComparisonMatrix ComparisonMatrix `json:"comparisonMatrix,omitempty"`
	Ticks Ticks `json:"ticks,omitempty"`
	PlotBands []PlotBand `json:"plotBands,omitempty"`
	RegionalScores []RegionalScore `json:"regionalScores,omitempty"`
	Uptime1m float32 `json:"uptime1m,omitempty"`
	Uptime6m float32 `json:"uptime6m,omitempty"`
}
