/*
 * siastats.info API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2019-10-03
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package siastats
// PlotBandLabel struct for PlotBandLabel
type PlotBandLabel struct {
	Text string `json:"text,omitempty"`
	Rotation int32 `json:"rotation,omitempty"`
	TextAlign string `json:"textAlign,omitempty"`
	Align string `json:"align,omitempty"`
	X int32 `json:"x,omitempty"`
	Y int32 `json:"y,omitempty"`
}
