/*
 * siastats.info API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2019-10-03
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package siastats
// PlotBand struct for PlotBand
type PlotBand struct {
	Color string `json:"color,omitempty"`
	From int64 `json:"from,omitempty"`
	To int64 `json:"to,omitempty"`
	Label PlotBandLabel `json:"label,omitempty"`
}
