/*
 * siastats.info API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2019-10-03
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package siastats
// RegionalScore struct for RegionalScore
type RegionalScore struct {
	Region string `json:"region,omitempty"`
	Latency int32 `json:"latency,omitempty"`
	Up string `json:"up,omitempty"`
	Down string `json:"down,omitempty"`
	LatencyScore int32 `json:"latencyScore,omitempty"`
	UpScore int32 `json:"upScore,omitempty"`
	DownScore int32 `json:"downScore,omitempty"`
	FinalScore int32 `json:"finalScore,omitempty"`
}
