/*
 * siastats.info API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2019-10-03
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package siastats
// Status struct for Status
type Status struct {
	Consensusblock int32 `json:"consensusblock,omitempty"`
	Lastblock int32 `json:"lastblock,omitempty"`
	Heartbeat int64 `json:"heartbeat,omitempty"`
	Peers int32 `json:"peers,omitempty"`
	Version string `json:"version,omitempty"`
}
