/*
 * siastats.info API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2019-10-03
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package siastats
// ComparisonMatrix struct for ComparisonMatrix
type ComparisonMatrix struct {
	Stored int32 `json:"stored,omitempty"`
	Price float32 `json:"price,omitempty"`
	Collateral float32 `json:"collateral,omitempty"`
	Up float32 `json:"up,omitempty"`
	Down float32 `json:"down,omitempty"`
	ContractPrice float32 `json:"contractPrice,omitempty"`
}
